version: '3.5'
services:
  front:
    build: frontend
    ports:
      - 3000:80
    depends_on:
      - app
  app:
    build: Gaz
    ports:
      - 8080:8080
    container_name: gaz
    restart: unless-stopped
    depends_on:
      - sql-server
    environment:
      - EMAIL_SENDER_ADDRESS=vanech12345@gmail.com
      - EMAIL_SENDER_PASSWORD=hnaxzkvwaiyxlptq
      - APP_PORT=8080
      - SHA_SALT=2ketgksdkepqwor[ptweoyiwjeijeasdnfdvberoiwpas,clvdknbftjlsa;x;,cvnbgreals;xzc,c,vnfdwow
      - JWT_SALT=legjliqjwoejrqfgeniowo4i3wipreq;ksdfjbgkhoiterwpq[lasdkmcvnbfjghutriowepq[als;dk,m,cvnkfjg
  sql-server:
    image: postgres
    ports:
      - '5432:5432'
    restart: unless-stopped
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root